2023-05-17 06:25:37,418:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:25:37,418:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:25:37,418:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:25:37,418:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:25:38,180:WARNING:
'prophet' is a soft dependency and not included in the pycaret installation. Please run: `pip install prophet` to install.
2023-05-17 06:25:38,679:INFO:PyCaret ClassificationExperiment
2023-05-17 06:25:38,679:INFO:Logging name: clf-default-name
2023-05-17 06:25:38,679:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-05-17 06:25:38,679:INFO:version 3.0.1
2023-05-17 06:25:38,679:INFO:Initializing setup()
2023-05-17 06:25:38,679:INFO:self.USI: 434c
2023-05-17 06:25:38,679:INFO:self._variable_keys: {'USI', '_available_plots', 'logging_param', 'fold_groups_param', 'X_train', 'memory', 'fold_generator', 'y', 'exp_id', 'gpu_n_jobs_param', 'target_param', '_ml_usecase', 'X_test', 'html_param', 'data', 'idx', 'n_jobs_param', 'seed', 'y_test', 'X', 'log_plots_param', 'y_train', 'exp_name_log', 'fix_imbalance', 'is_multiclass', 'fold_shuffle_param', 'gpu_param', 'pipeline'}
2023-05-17 06:25:38,679:INFO:Checking environment
2023-05-17 06:25:38,679:INFO:python_version: 3.9.13
2023-05-17 06:25:38,679:INFO:python_build: ('main', 'Aug 25 2022 23:51:50')
2023-05-17 06:25:38,679:INFO:machine: AMD64
2023-05-17 06:25:38,679:INFO:platform: Windows-10-10.0.22621-SP0
2023-05-17 06:25:38,679:INFO:Memory: svmem(total=8376061952, available=953896960, percent=88.6, used=7422164992, free=953896960)
2023-05-17 06:25:38,679:INFO:Physical Core: 6
2023-05-17 06:25:38,679:INFO:Logical Core: 12
2023-05-17 06:25:38,679:INFO:Checking libraries
2023-05-17 06:25:38,679:INFO:System:
2023-05-17 06:25:38,679:INFO:    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
2023-05-17 06:25:38,679:INFO:executable: C:\Users\Beboo\anaconda3\python.exe
2023-05-17 06:25:38,679:INFO:   machine: Windows-10-10.0.22621-SP0
2023-05-17 06:25:38,695:INFO:PyCaret required dependencies:
2023-05-17 06:25:38,695:INFO:                 pip: 22.2.2
2023-05-17 06:25:38,695:INFO:          setuptools: 63.4.1
2023-05-17 06:25:38,695:INFO:             pycaret: 3.0.1
2023-05-17 06:25:38,695:INFO:             IPython: 7.31.1
2023-05-17 06:25:38,695:INFO:          ipywidgets: 7.6.5
2023-05-17 06:25:38,695:INFO:                tqdm: 4.64.1
2023-05-17 06:25:38,695:INFO:               numpy: 1.21.5
2023-05-17 06:25:38,695:INFO:              pandas: 1.4.4
2023-05-17 06:25:38,695:INFO:              jinja2: 2.11.3
2023-05-17 06:25:38,695:INFO:               scipy: 1.9.1
2023-05-17 06:25:38,695:INFO:              joblib: 1.2.0
2023-05-17 06:25:38,695:INFO:             sklearn: 1.0.2
2023-05-17 06:25:38,695:INFO:                pyod: 1.0.9
2023-05-17 06:25:38,695:INFO:            imblearn: 0.10.1
2023-05-17 06:25:38,695:INFO:   category_encoders: 2.6.0
2023-05-17 06:25:38,695:INFO:            lightgbm: 3.3.5
2023-05-17 06:25:38,695:INFO:               numba: 0.55.1
2023-05-17 06:25:38,695:INFO:            requests: 2.28.1
2023-05-17 06:25:38,695:INFO:          matplotlib: 3.5.2
2023-05-17 06:25:38,695:INFO:          scikitplot: 0.3.7
2023-05-17 06:25:38,695:INFO:         yellowbrick: 1.5
2023-05-17 06:25:38,695:INFO:              plotly: 5.9.0
2023-05-17 06:25:38,695:INFO:             kaleido: 0.2.1
2023-05-17 06:25:38,695:INFO:         statsmodels: 0.13.2
2023-05-17 06:25:38,695:INFO:              sktime: 0.17.0
2023-05-17 06:25:38,695:INFO:               tbats: 1.1.3
2023-05-17 06:25:38,695:INFO:            pmdarima: 2.0.3
2023-05-17 06:25:38,695:INFO:              psutil: 5.9.0
2023-05-17 06:25:38,695:INFO:PyCaret optional dependencies:
2023-05-17 06:25:38,709:INFO:                shap: Not installed
2023-05-17 06:25:38,709:INFO:           interpret: Not installed
2023-05-17 06:25:38,709:INFO:                umap: Not installed
2023-05-17 06:25:38,709:INFO:    pandas_profiling: Not installed
2023-05-17 06:25:38,709:INFO:  explainerdashboard: Not installed
2023-05-17 06:25:38,709:INFO:             autoviz: Not installed
2023-05-17 06:25:38,709:INFO:           fairlearn: Not installed
2023-05-17 06:25:38,709:INFO:             xgboost: 1.7.5
2023-05-17 06:25:38,709:INFO:            catboost: 1.2
2023-05-17 06:25:38,709:INFO:              kmodes: Not installed
2023-05-17 06:25:38,710:INFO:             mlxtend: Not installed
2023-05-17 06:25:38,710:INFO:       statsforecast: Not installed
2023-05-17 06:25:38,710:INFO:        tune_sklearn: Not installed
2023-05-17 06:25:38,710:INFO:                 ray: Not installed
2023-05-17 06:25:38,710:INFO:            hyperopt: Not installed
2023-05-17 06:25:38,710:INFO:              optuna: Not installed
2023-05-17 06:25:38,710:INFO:               skopt: Not installed
2023-05-17 06:25:38,710:INFO:              mlflow: Not installed
2023-05-17 06:25:38,710:INFO:              gradio: Not installed
2023-05-17 06:25:38,710:INFO:             fastapi: Not installed
2023-05-17 06:25:38,710:INFO:             uvicorn: Not installed
2023-05-17 06:25:38,710:INFO:              m2cgen: Not installed
2023-05-17 06:25:38,710:INFO:           evidently: Not installed
2023-05-17 06:25:38,710:INFO:               fugue: Not installed
2023-05-17 06:25:38,710:INFO:           streamlit: Not installed
2023-05-17 06:25:38,710:INFO:             prophet: Not installed
2023-05-17 06:25:38,710:INFO:None
2023-05-17 06:25:38,710:INFO:Set up data.
2023-05-17 06:25:38,715:INFO:Set up train/test split.
2023-05-17 06:25:38,719:INFO:Set up index.
2023-05-17 06:25:38,720:INFO:Set up folding strategy.
2023-05-17 06:25:38,720:INFO:Assigning column types.
2023-05-17 06:25:38,722:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-05-17 06:25:38,762:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,763:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,785:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:38,785:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:38,832:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,833:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,859:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:38,861:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:38,862:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-05-17 06:25:38,903:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,928:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:38,930:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:38,972:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:25:38,996:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:38,998:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:38,999:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-05-17 06:25:39,065:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:39,067:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:39,134:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:39,134:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:39,139:INFO:Preparing preprocessing pipeline...
2023-05-17 06:25:39,141:INFO:Set up simple imputation.
2023-05-17 06:25:39,173:INFO:Finished creating preprocessing pipeline.
2023-05-17 06:25:39,177:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\Beboo\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Pregnancies', 'Glucose',
                                             'BloodPressure', 'SkinThickness',
                                             'Insulin', 'BMI',
                                             'DiabetesPedigreeFunction', 'Age',
                                             'age_bins'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose=0))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose=0)))],
         verbose=False)
2023-05-17 06:25:39,177:INFO:Creating final display dataframe.
2023-05-17 06:25:39,235:INFO:Setup _display_container:                     Description             Value
0                    Session id              6795
1                        Target           Outcome
2                   Target type            Binary
3           Original data shape         (537, 10)
4        Transformed data shape         (537, 10)
5   Transformed train set shape         (375, 10)
6    Transformed test set shape         (162, 10)
7              Numeric features                 9
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              434c
2023-05-17 06:25:39,303:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:39,312:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:39,370:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:25:39,370:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:25:39,370:INFO:setup() successfully completed in 1.05s...............
2023-05-17 06:25:39,370:INFO:Initializing compare_models()
2023-05-17 06:25:39,370:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-05-17 06:25:39,370:INFO:Checking exceptions
2023-05-17 06:25:39,370:INFO:Preparing display monitor
2023-05-17 06:25:39,419:INFO:Initializing Logistic Regression
2023-05-17 06:25:39,419:INFO:Total runtime is 0.0 minutes
2023-05-17 06:25:39,423:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:39,423:INFO:Initializing create_model()
2023-05-17 06:25:39,423:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:39,424:INFO:Checking exceptions
2023-05-17 06:25:39,424:INFO:Importing libraries
2023-05-17 06:25:39,424:INFO:Copying training dataset
2023-05-17 06:25:39,427:INFO:Defining folds
2023-05-17 06:25:39,427:INFO:Declaring metric variables
2023-05-17 06:25:39,430:INFO:Importing untrained model
2023-05-17 06:25:39,434:INFO:Logistic Regression Imported successfully
2023-05-17 06:25:39,438:INFO:Starting cross validation
2023-05-17 06:25:39,438:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:48,210:INFO:Calculating mean and std
2023-05-17 06:25:48,227:INFO:Creating metrics dataframe
2023-05-17 06:25:48,408:INFO:Uploading results into container
2023-05-17 06:25:48,408:INFO:Uploading model into container now
2023-05-17 06:25:48,409:INFO:_master_model_container: 1
2023-05-17 06:25:48,409:INFO:_display_container: 2
2023-05-17 06:25:48,410:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6795, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:25:48,410:INFO:create_model() successfully completed......................................
2023-05-17 06:25:48,499:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:48,499:INFO:Creating metrics dataframe
2023-05-17 06:25:48,510:INFO:Initializing K Neighbors Classifier
2023-05-17 06:25:48,510:INFO:Total runtime is 0.1515120307604472 minutes
2023-05-17 06:25:48,514:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:48,514:INFO:Initializing create_model()
2023-05-17 06:25:48,515:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:48,515:INFO:Checking exceptions
2023-05-17 06:25:48,515:INFO:Importing libraries
2023-05-17 06:25:48,515:INFO:Copying training dataset
2023-05-17 06:25:48,519:INFO:Defining folds
2023-05-17 06:25:48,520:INFO:Declaring metric variables
2023-05-17 06:25:48,523:INFO:Importing untrained model
2023-05-17 06:25:48,526:INFO:K Neighbors Classifier Imported successfully
2023-05-17 06:25:48,533:INFO:Starting cross validation
2023-05-17 06:25:48,534:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:48,623:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,625:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,634:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,639:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,639:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,660:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,667:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:48,676:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:51,189:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:51,189:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:25:51,338:INFO:Calculating mean and std
2023-05-17 06:25:51,338:INFO:Creating metrics dataframe
2023-05-17 06:25:51,510:INFO:Uploading results into container
2023-05-17 06:25:51,510:INFO:Uploading model into container now
2023-05-17 06:25:51,510:INFO:_master_model_container: 2
2023-05-17 06:25:51,510:INFO:_display_container: 2
2023-05-17 06:25:51,510:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-05-17 06:25:51,510:INFO:create_model() successfully completed......................................
2023-05-17 06:25:51,601:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:51,602:INFO:Creating metrics dataframe
2023-05-17 06:25:51,613:INFO:Initializing Naive Bayes
2023-05-17 06:25:51,613:INFO:Total runtime is 0.20323926607767742 minutes
2023-05-17 06:25:51,617:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:51,618:INFO:Initializing create_model()
2023-05-17 06:25:51,618:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:51,618:INFO:Checking exceptions
2023-05-17 06:25:51,618:INFO:Importing libraries
2023-05-17 06:25:51,618:INFO:Copying training dataset
2023-05-17 06:25:51,622:INFO:Defining folds
2023-05-17 06:25:51,622:INFO:Declaring metric variables
2023-05-17 06:25:51,627:INFO:Importing untrained model
2023-05-17 06:25:51,630:INFO:Naive Bayes Imported successfully
2023-05-17 06:25:51,632:INFO:Starting cross validation
2023-05-17 06:25:51,632:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:52,831:INFO:Calculating mean and std
2023-05-17 06:25:52,832:INFO:Creating metrics dataframe
2023-05-17 06:25:53,002:INFO:Uploading results into container
2023-05-17 06:25:53,003:INFO:Uploading model into container now
2023-05-17 06:25:53,004:INFO:_master_model_container: 3
2023-05-17 06:25:53,004:INFO:_display_container: 2
2023-05-17 06:25:53,004:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-05-17 06:25:53,004:INFO:create_model() successfully completed......................................
2023-05-17 06:25:53,077:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:53,077:INFO:Creating metrics dataframe
2023-05-17 06:25:53,096:INFO:Initializing Decision Tree Classifier
2023-05-17 06:25:53,096:INFO:Total runtime is 0.2279477914174398 minutes
2023-05-17 06:25:53,100:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:53,100:INFO:Initializing create_model()
2023-05-17 06:25:53,100:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:53,100:INFO:Checking exceptions
2023-05-17 06:25:53,100:INFO:Importing libraries
2023-05-17 06:25:53,100:INFO:Copying training dataset
2023-05-17 06:25:53,104:INFO:Defining folds
2023-05-17 06:25:53,105:INFO:Declaring metric variables
2023-05-17 06:25:53,108:INFO:Importing untrained model
2023-05-17 06:25:53,109:INFO:Decision Tree Classifier Imported successfully
2023-05-17 06:25:53,109:INFO:Starting cross validation
2023-05-17 06:25:53,109:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:54,298:INFO:Calculating mean and std
2023-05-17 06:25:54,298:INFO:Creating metrics dataframe
2023-05-17 06:25:54,473:INFO:Uploading results into container
2023-05-17 06:25:54,473:INFO:Uploading model into container now
2023-05-17 06:25:54,473:INFO:_master_model_container: 4
2023-05-17 06:25:54,473:INFO:_display_container: 2
2023-05-17 06:25:54,473:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=6795, splitter='best')
2023-05-17 06:25:54,473:INFO:create_model() successfully completed......................................
2023-05-17 06:25:54,557:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:54,557:INFO:Creating metrics dataframe
2023-05-17 06:25:54,580:INFO:Initializing SVM - Linear Kernel
2023-05-17 06:25:54,580:INFO:Total runtime is 0.25267906983693444 minutes
2023-05-17 06:25:54,584:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:54,584:INFO:Initializing create_model()
2023-05-17 06:25:54,584:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:54,585:INFO:Checking exceptions
2023-05-17 06:25:54,585:INFO:Importing libraries
2023-05-17 06:25:54,585:INFO:Copying training dataset
2023-05-17 06:25:54,589:INFO:Defining folds
2023-05-17 06:25:54,590:INFO:Declaring metric variables
2023-05-17 06:25:54,593:INFO:Importing untrained model
2023-05-17 06:25:54,597:INFO:SVM - Linear Kernel Imported successfully
2023-05-17 06:25:54,609:INFO:Starting cross validation
2023-05-17 06:25:54,609:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:54,940:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,940:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,941:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,941:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,942:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,942:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,943:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,946:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:25:54,979:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:25:54,980:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:25:56,076:INFO:Calculating mean and std
2023-05-17 06:25:56,078:INFO:Creating metrics dataframe
2023-05-17 06:25:56,250:INFO:Uploading results into container
2023-05-17 06:25:56,250:INFO:Uploading model into container now
2023-05-17 06:25:56,250:INFO:_master_model_container: 5
2023-05-17 06:25:56,250:INFO:_display_container: 2
2023-05-17 06:25:56,250:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=6795, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-05-17 06:25:56,250:INFO:create_model() successfully completed......................................
2023-05-17 06:25:56,323:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:56,323:INFO:Creating metrics dataframe
2023-05-17 06:25:56,338:INFO:Initializing Ridge Classifier
2023-05-17 06:25:56,338:INFO:Total runtime is 0.28199072281519577 minutes
2023-05-17 06:25:56,338:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:56,338:INFO:Initializing create_model()
2023-05-17 06:25:56,338:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:56,338:INFO:Checking exceptions
2023-05-17 06:25:56,338:INFO:Importing libraries
2023-05-17 06:25:56,338:INFO:Copying training dataset
2023-05-17 06:25:56,353:INFO:Defining folds
2023-05-17 06:25:56,353:INFO:Declaring metric variables
2023-05-17 06:25:56,357:INFO:Importing untrained model
2023-05-17 06:25:56,361:INFO:Ridge Classifier Imported successfully
2023-05-17 06:25:56,361:INFO:Starting cross validation
2023-05-17 06:25:56,361:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:56,442:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,442:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,458:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,458:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,458:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,458:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,458:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,473:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,473:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:56,489:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:25:57,595:INFO:Calculating mean and std
2023-05-17 06:25:57,595:INFO:Creating metrics dataframe
2023-05-17 06:25:57,784:INFO:Uploading results into container
2023-05-17 06:25:57,785:INFO:Uploading model into container now
2023-05-17 06:25:57,786:INFO:_master_model_container: 6
2023-05-17 06:25:57,786:INFO:_display_container: 2
2023-05-17 06:25:57,786:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize='deprecated', positive=False,
                random_state=6795, solver='auto', tol=0.001)
2023-05-17 06:25:57,787:INFO:create_model() successfully completed......................................
2023-05-17 06:25:57,872:INFO:SubProcess create_model() end ==================================
2023-05-17 06:25:57,872:INFO:Creating metrics dataframe
2023-05-17 06:25:57,887:INFO:Initializing Random Forest Classifier
2023-05-17 06:25:57,887:INFO:Total runtime is 0.3078059077262879 minutes
2023-05-17 06:25:57,901:INFO:SubProcess create_model() called ==================================
2023-05-17 06:25:57,902:INFO:Initializing create_model()
2023-05-17 06:25:57,902:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:25:57,902:INFO:Checking exceptions
2023-05-17 06:25:57,902:INFO:Importing libraries
2023-05-17 06:25:57,902:INFO:Copying training dataset
2023-05-17 06:25:57,911:INFO:Defining folds
2023-05-17 06:25:57,912:INFO:Declaring metric variables
2023-05-17 06:25:57,917:INFO:Importing untrained model
2023-05-17 06:25:57,924:INFO:Random Forest Classifier Imported successfully
2023-05-17 06:25:57,939:INFO:Starting cross validation
2023-05-17 06:25:57,940:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:25:59,996:INFO:Calculating mean and std
2023-05-17 06:25:59,996:INFO:Creating metrics dataframe
2023-05-17 06:26:00,177:INFO:Uploading results into container
2023-05-17 06:26:00,177:INFO:Uploading model into container now
2023-05-17 06:26:00,177:INFO:_master_model_container: 7
2023-05-17 06:26:00,177:INFO:_display_container: 2
2023-05-17 06:26:00,177:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6795, verbose=0, warm_start=False)
2023-05-17 06:26:00,177:INFO:create_model() successfully completed......................................
2023-05-17 06:26:00,261:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:00,261:INFO:Creating metrics dataframe
2023-05-17 06:26:00,278:INFO:Initializing Quadratic Discriminant Analysis
2023-05-17 06:26:00,278:INFO:Total runtime is 0.34764558076858526 minutes
2023-05-17 06:26:00,278:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:00,278:INFO:Initializing create_model()
2023-05-17 06:26:00,278:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:00,278:INFO:Checking exceptions
2023-05-17 06:26:00,278:INFO:Importing libraries
2023-05-17 06:26:00,278:INFO:Copying training dataset
2023-05-17 06:26:00,278:INFO:Defining folds
2023-05-17 06:26:00,278:INFO:Declaring metric variables
2023-05-17 06:26:00,295:INFO:Importing untrained model
2023-05-17 06:26:00,298:INFO:Quadratic Discriminant Analysis Imported successfully
2023-05-17 06:26:00,304:INFO:Starting cross validation
2023-05-17 06:26:00,305:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:01,533:INFO:Calculating mean and std
2023-05-17 06:26:01,534:INFO:Creating metrics dataframe
2023-05-17 06:26:01,712:INFO:Uploading results into container
2023-05-17 06:26:01,713:INFO:Uploading model into container now
2023-05-17 06:26:01,714:INFO:_master_model_container: 8
2023-05-17 06:26:01,714:INFO:_display_container: 2
2023-05-17 06:26:01,714:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-05-17 06:26:01,714:INFO:create_model() successfully completed......................................
2023-05-17 06:26:01,776:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:01,776:INFO:Creating metrics dataframe
2023-05-17 06:26:01,792:INFO:Initializing Ada Boost Classifier
2023-05-17 06:26:01,792:INFO:Total runtime is 0.3728843967119853 minutes
2023-05-17 06:26:01,808:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:01,808:INFO:Initializing create_model()
2023-05-17 06:26:01,808:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:01,808:INFO:Checking exceptions
2023-05-17 06:26:01,808:INFO:Importing libraries
2023-05-17 06:26:01,808:INFO:Copying training dataset
2023-05-17 06:26:01,808:INFO:Defining folds
2023-05-17 06:26:01,808:INFO:Declaring metric variables
2023-05-17 06:26:01,808:INFO:Importing untrained model
2023-05-17 06:26:01,808:INFO:Ada Boost Classifier Imported successfully
2023-05-17 06:26:01,823:INFO:Starting cross validation
2023-05-17 06:26:01,823:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:03,195:INFO:Calculating mean and std
2023-05-17 06:26:03,195:INFO:Creating metrics dataframe
2023-05-17 06:26:03,382:INFO:Uploading results into container
2023-05-17 06:26:03,383:INFO:Uploading model into container now
2023-05-17 06:26:03,383:INFO:_master_model_container: 9
2023-05-17 06:26:03,383:INFO:_display_container: 2
2023-05-17 06:26:03,384:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=6795)
2023-05-17 06:26:03,384:INFO:create_model() successfully completed......................................
2023-05-17 06:26:03,462:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:03,462:INFO:Creating metrics dataframe
2023-05-17 06:26:03,475:INFO:Initializing Gradient Boosting Classifier
2023-05-17 06:26:03,476:INFO:Total runtime is 0.4009442249933879 minutes
2023-05-17 06:26:03,479:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:03,479:INFO:Initializing create_model()
2023-05-17 06:26:03,480:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:03,480:INFO:Checking exceptions
2023-05-17 06:26:03,480:INFO:Importing libraries
2023-05-17 06:26:03,480:INFO:Copying training dataset
2023-05-17 06:26:03,484:INFO:Defining folds
2023-05-17 06:26:03,485:INFO:Declaring metric variables
2023-05-17 06:26:03,488:INFO:Importing untrained model
2023-05-17 06:26:03,491:INFO:Gradient Boosting Classifier Imported successfully
2023-05-17 06:26:03,497:INFO:Starting cross validation
2023-05-17 06:26:03,498:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:05,047:INFO:Calculating mean and std
2023-05-17 06:26:05,047:INFO:Creating metrics dataframe
2023-05-17 06:26:05,230:INFO:Uploading results into container
2023-05-17 06:26:05,230:INFO:Uploading model into container now
2023-05-17 06:26:05,230:INFO:_master_model_container: 10
2023-05-17 06:26:05,230:INFO:_display_container: 2
2023-05-17 06:26:05,230:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6795, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-05-17 06:26:05,230:INFO:create_model() successfully completed......................................
2023-05-17 06:26:05,314:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:05,314:INFO:Creating metrics dataframe
2023-05-17 06:26:05,330:INFO:Initializing Linear Discriminant Analysis
2023-05-17 06:26:05,330:INFO:Total runtime is 0.4318552096684774 minutes
2023-05-17 06:26:05,330:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:05,330:INFO:Initializing create_model()
2023-05-17 06:26:05,330:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:05,330:INFO:Checking exceptions
2023-05-17 06:26:05,330:INFO:Importing libraries
2023-05-17 06:26:05,330:INFO:Copying training dataset
2023-05-17 06:26:05,330:INFO:Defining folds
2023-05-17 06:26:05,330:INFO:Declaring metric variables
2023-05-17 06:26:05,345:INFO:Importing untrained model
2023-05-17 06:26:05,349:INFO:Linear Discriminant Analysis Imported successfully
2023-05-17 06:26:05,355:INFO:Starting cross validation
2023-05-17 06:26:05,356:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:06,641:INFO:Calculating mean and std
2023-05-17 06:26:06,657:INFO:Creating metrics dataframe
2023-05-17 06:26:06,834:INFO:Uploading results into container
2023-05-17 06:26:06,834:INFO:Uploading model into container now
2023-05-17 06:26:06,834:INFO:_master_model_container: 11
2023-05-17 06:26:06,834:INFO:_display_container: 2
2023-05-17 06:26:06,834:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-05-17 06:26:06,834:INFO:create_model() successfully completed......................................
2023-05-17 06:26:06,911:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:06,911:INFO:Creating metrics dataframe
2023-05-17 06:26:06,926:INFO:Initializing Extra Trees Classifier
2023-05-17 06:26:06,926:INFO:Total runtime is 0.45844996770222984 minutes
2023-05-17 06:26:06,926:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:06,926:INFO:Initializing create_model()
2023-05-17 06:26:06,926:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:06,926:INFO:Checking exceptions
2023-05-17 06:26:06,926:INFO:Importing libraries
2023-05-17 06:26:06,926:INFO:Copying training dataset
2023-05-17 06:26:06,940:INFO:Defining folds
2023-05-17 06:26:06,940:INFO:Declaring metric variables
2023-05-17 06:26:06,944:INFO:Importing untrained model
2023-05-17 06:26:06,948:INFO:Extra Trees Classifier Imported successfully
2023-05-17 06:26:06,949:INFO:Starting cross validation
2023-05-17 06:26:06,949:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:08,887:INFO:Calculating mean and std
2023-05-17 06:26:08,888:INFO:Creating metrics dataframe
2023-05-17 06:26:09,075:INFO:Uploading results into container
2023-05-17 06:26:09,075:INFO:Uploading model into container now
2023-05-17 06:26:09,075:INFO:_master_model_container: 12
2023-05-17 06:26:09,075:INFO:_display_container: 2
2023-05-17 06:26:09,075:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=6795, verbose=0, warm_start=False)
2023-05-17 06:26:09,075:INFO:create_model() successfully completed......................................
2023-05-17 06:26:09,145:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:09,145:INFO:Creating metrics dataframe
2023-05-17 06:26:09,161:INFO:Initializing Extreme Gradient Boosting
2023-05-17 06:26:09,161:INFO:Total runtime is 0.4957007209459941 minutes
2023-05-17 06:26:09,173:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:09,173:INFO:Initializing create_model()
2023-05-17 06:26:09,173:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:09,173:INFO:Checking exceptions
2023-05-17 06:26:09,173:INFO:Importing libraries
2023-05-17 06:26:09,173:INFO:Copying training dataset
2023-05-17 06:26:09,178:INFO:Defining folds
2023-05-17 06:26:09,178:INFO:Declaring metric variables
2023-05-17 06:26:09,182:INFO:Importing untrained model
2023-05-17 06:26:09,184:INFO:Extreme Gradient Boosting Imported successfully
2023-05-17 06:26:09,198:INFO:Starting cross validation
2023-05-17 06:26:09,198:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:10,678:INFO:Calculating mean and std
2023-05-17 06:26:10,678:INFO:Creating metrics dataframe
2023-05-17 06:26:10,877:INFO:Uploading results into container
2023-05-17 06:26:10,877:INFO:Uploading model into container now
2023-05-17 06:26:10,877:INFO:_master_model_container: 13
2023-05-17 06:26:10,877:INFO:_display_container: 2
2023-05-17 06:26:10,877:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)
2023-05-17 06:26:10,877:INFO:create_model() successfully completed......................................
2023-05-17 06:26:10,948:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:10,948:INFO:Creating metrics dataframe
2023-05-17 06:26:10,963:INFO:Initializing Light Gradient Boosting Machine
2023-05-17 06:26:10,963:INFO:Total runtime is 0.5257297396659851 minutes
2023-05-17 06:26:10,963:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:10,963:INFO:Initializing create_model()
2023-05-17 06:26:10,978:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:10,978:INFO:Checking exceptions
2023-05-17 06:26:10,978:INFO:Importing libraries
2023-05-17 06:26:10,978:INFO:Copying training dataset
2023-05-17 06:26:10,983:INFO:Defining folds
2023-05-17 06:26:10,983:INFO:Declaring metric variables
2023-05-17 06:26:10,987:INFO:Importing untrained model
2023-05-17 06:26:10,990:INFO:Light Gradient Boosting Machine Imported successfully
2023-05-17 06:26:10,997:INFO:Starting cross validation
2023-05-17 06:26:10,998:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:13,782:INFO:Calculating mean and std
2023-05-17 06:26:13,782:INFO:Creating metrics dataframe
2023-05-17 06:26:13,980:INFO:Uploading results into container
2023-05-17 06:26:13,981:INFO:Uploading model into container now
2023-05-17 06:26:13,981:INFO:_master_model_container: 14
2023-05-17 06:26:13,981:INFO:_display_container: 2
2023-05-17 06:26:13,982:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6795, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2023-05-17 06:26:13,982:INFO:create_model() successfully completed......................................
2023-05-17 06:26:14,066:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:14,066:INFO:Creating metrics dataframe
2023-05-17 06:26:14,077:INFO:Initializing CatBoost Classifier
2023-05-17 06:26:14,078:INFO:Total runtime is 0.5776527762413025 minutes
2023-05-17 06:26:14,081:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:14,081:INFO:Initializing create_model()
2023-05-17 06:26:14,081:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:14,081:INFO:Checking exceptions
2023-05-17 06:26:14,081:INFO:Importing libraries
2023-05-17 06:26:14,081:INFO:Copying training dataset
2023-05-17 06:26:14,085:INFO:Defining folds
2023-05-17 06:26:14,086:INFO:Declaring metric variables
2023-05-17 06:26:14,089:INFO:Importing untrained model
2023-05-17 06:26:14,093:INFO:CatBoost Classifier Imported successfully
2023-05-17 06:26:14,101:INFO:Starting cross validation
2023-05-17 06:26:14,102:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:22,687:INFO:Calculating mean and std
2023-05-17 06:26:22,688:INFO:Creating metrics dataframe
2023-05-17 06:26:22,871:INFO:Uploading results into container
2023-05-17 06:26:22,887:INFO:Uploading model into container now
2023-05-17 06:26:22,887:INFO:_master_model_container: 15
2023-05-17 06:26:22,887:INFO:_display_container: 2
2023-05-17 06:26:22,887:INFO:<catboost.core.CatBoostClassifier object at 0x0000024C729D58B0>
2023-05-17 06:26:22,887:INFO:create_model() successfully completed......................................
2023-05-17 06:26:22,968:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:22,968:INFO:Creating metrics dataframe
2023-05-17 06:26:22,986:INFO:Initializing Dummy Classifier
2023-05-17 06:26:22,986:INFO:Total runtime is 0.7261256376902263 minutes
2023-05-17 06:26:22,990:INFO:SubProcess create_model() called ==================================
2023-05-17 06:26:22,990:INFO:Initializing create_model()
2023-05-17 06:26:22,990:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000024C72B3E580>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:22,990:INFO:Checking exceptions
2023-05-17 06:26:22,990:INFO:Importing libraries
2023-05-17 06:26:22,990:INFO:Copying training dataset
2023-05-17 06:26:22,995:INFO:Defining folds
2023-05-17 06:26:22,995:INFO:Declaring metric variables
2023-05-17 06:26:22,998:INFO:Importing untrained model
2023-05-17 06:26:23,001:INFO:Dummy Classifier Imported successfully
2023-05-17 06:26:23,004:INFO:Starting cross validation
2023-05-17 06:26:23,004:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:26:23,086:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,102:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,118:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,118:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,118:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,143:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,144:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,154:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,154:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:23,154:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:26:24,351:INFO:Calculating mean and std
2023-05-17 06:26:24,351:INFO:Creating metrics dataframe
2023-05-17 06:26:24,543:INFO:Uploading results into container
2023-05-17 06:26:24,543:INFO:Uploading model into container now
2023-05-17 06:26:24,543:INFO:_master_model_container: 16
2023-05-17 06:26:24,543:INFO:_display_container: 2
2023-05-17 06:26:24,543:INFO:DummyClassifier(constant=None, random_state=6795, strategy='prior')
2023-05-17 06:26:24,543:INFO:create_model() successfully completed......................................
2023-05-17 06:26:24,618:INFO:SubProcess create_model() end ==================================
2023-05-17 06:26:24,618:INFO:Creating metrics dataframe
2023-05-17 06:26:24,653:INFO:Initializing create_model()
2023-05-17 06:26:24,653:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000024C66209460>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6795, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:26:24,653:INFO:Checking exceptions
2023-05-17 06:26:24,653:INFO:Importing libraries
2023-05-17 06:26:24,653:INFO:Copying training dataset
2023-05-17 06:26:24,653:INFO:Defining folds
2023-05-17 06:26:24,653:INFO:Declaring metric variables
2023-05-17 06:26:24,653:INFO:Importing untrained model
2023-05-17 06:26:24,653:INFO:Declaring custom model
2023-05-17 06:26:24,653:INFO:Logistic Regression Imported successfully
2023-05-17 06:26:24,653:INFO:Cross validation set to False
2023-05-17 06:26:24,653:INFO:Fitting Model
2023-05-17 06:26:24,839:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6795, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:26:24,839:INFO:create_model() successfully completed......................................
2023-05-17 06:26:24,961:INFO:_master_model_container: 16
2023-05-17 06:26:24,961:INFO:_display_container: 2
2023-05-17 06:26:24,961:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6795, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:26:24,961:INFO:compare_models() successfully completed......................................
2023-05-17 06:30:18,886:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:30:18,886:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:30:18,886:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:30:18,886:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-17 06:30:19,628:WARNING:
'prophet' is a soft dependency and not included in the pycaret installation. Please run: `pip install prophet` to install.
2023-05-17 06:30:19,909:INFO:PyCaret ClassificationExperiment
2023-05-17 06:30:19,909:INFO:Logging name: clf-default-name
2023-05-17 06:30:19,909:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-05-17 06:30:19,909:INFO:version 3.0.1
2023-05-17 06:30:19,909:INFO:Initializing setup()
2023-05-17 06:30:19,909:INFO:self.USI: 93b6
2023-05-17 06:30:19,909:INFO:self._variable_keys: {'y', 'fix_imbalance', 'n_jobs_param', 'html_param', 'exp_id', 'memory', 'USI', 'fold_generator', 'fold_shuffle_param', 'fold_groups_param', 'data', 'y_test', 'seed', 'pipeline', 'gpu_n_jobs_param', 'is_multiclass', 'y_train', '_ml_usecase', 'idx', 'exp_name_log', 'logging_param', 'log_plots_param', 'target_param', 'X_train', 'X_test', 'X', '_available_plots', 'gpu_param'}
2023-05-17 06:30:19,909:INFO:Checking environment
2023-05-17 06:30:19,909:INFO:python_version: 3.9.13
2023-05-17 06:30:19,909:INFO:python_build: ('main', 'Aug 25 2022 23:51:50')
2023-05-17 06:30:19,909:INFO:machine: AMD64
2023-05-17 06:30:19,909:INFO:platform: Windows-10-10.0.22621-SP0
2023-05-17 06:30:19,909:INFO:Memory: svmem(total=8376061952, available=2839113728, percent=66.1, used=5536948224, free=2839113728)
2023-05-17 06:30:19,909:INFO:Physical Core: 6
2023-05-17 06:30:19,909:INFO:Logical Core: 12
2023-05-17 06:30:19,909:INFO:Checking libraries
2023-05-17 06:30:19,909:INFO:System:
2023-05-17 06:30:19,909:INFO:    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
2023-05-17 06:30:19,909:INFO:executable: C:\Users\Beboo\anaconda3\python.exe
2023-05-17 06:30:19,909:INFO:   machine: Windows-10-10.0.22621-SP0
2023-05-17 06:30:19,909:INFO:PyCaret required dependencies:
2023-05-17 06:30:19,909:INFO:                 pip: 22.2.2
2023-05-17 06:30:19,909:INFO:          setuptools: 63.4.1
2023-05-17 06:30:19,909:INFO:             pycaret: 3.0.1
2023-05-17 06:30:19,909:INFO:             IPython: 7.31.1
2023-05-17 06:30:19,909:INFO:          ipywidgets: 7.6.5
2023-05-17 06:30:19,909:INFO:                tqdm: 4.64.1
2023-05-17 06:30:19,909:INFO:               numpy: 1.21.5
2023-05-17 06:30:19,909:INFO:              pandas: 1.4.4
2023-05-17 06:30:19,909:INFO:              jinja2: 2.11.3
2023-05-17 06:30:19,909:INFO:               scipy: 1.9.1
2023-05-17 06:30:19,909:INFO:              joblib: 1.2.0
2023-05-17 06:30:19,909:INFO:             sklearn: 1.0.2
2023-05-17 06:30:19,909:INFO:                pyod: 1.0.9
2023-05-17 06:30:19,909:INFO:            imblearn: 0.10.1
2023-05-17 06:30:19,909:INFO:   category_encoders: 2.6.0
2023-05-17 06:30:19,909:INFO:            lightgbm: 3.3.5
2023-05-17 06:30:19,909:INFO:               numba: 0.55.1
2023-05-17 06:30:19,909:INFO:            requests: 2.28.1
2023-05-17 06:30:19,909:INFO:          matplotlib: 3.5.2
2023-05-17 06:30:19,909:INFO:          scikitplot: 0.3.7
2023-05-17 06:30:19,909:INFO:         yellowbrick: 1.5
2023-05-17 06:30:19,909:INFO:              plotly: 5.9.0
2023-05-17 06:30:19,909:INFO:             kaleido: 0.2.1
2023-05-17 06:30:19,909:INFO:         statsmodels: 0.13.2
2023-05-17 06:30:19,909:INFO:              sktime: 0.17.0
2023-05-17 06:30:19,909:INFO:               tbats: 1.1.3
2023-05-17 06:30:19,909:INFO:            pmdarima: 2.0.3
2023-05-17 06:30:19,909:INFO:              psutil: 5.9.0
2023-05-17 06:30:19,909:INFO:PyCaret optional dependencies:
2023-05-17 06:30:19,925:INFO:                shap: Not installed
2023-05-17 06:30:19,925:INFO:           interpret: Not installed
2023-05-17 06:30:19,925:INFO:                umap: Not installed
2023-05-17 06:30:19,925:INFO:    pandas_profiling: Not installed
2023-05-17 06:30:19,925:INFO:  explainerdashboard: Not installed
2023-05-17 06:30:19,925:INFO:             autoviz: Not installed
2023-05-17 06:30:19,925:INFO:           fairlearn: Not installed
2023-05-17 06:30:19,925:INFO:             xgboost: 1.7.5
2023-05-17 06:30:19,925:INFO:            catboost: 1.2
2023-05-17 06:30:19,925:INFO:              kmodes: Not installed
2023-05-17 06:30:19,925:INFO:             mlxtend: Not installed
2023-05-17 06:30:19,925:INFO:       statsforecast: Not installed
2023-05-17 06:30:19,925:INFO:        tune_sklearn: Not installed
2023-05-17 06:30:19,925:INFO:                 ray: Not installed
2023-05-17 06:30:19,925:INFO:            hyperopt: Not installed
2023-05-17 06:30:19,925:INFO:              optuna: Not installed
2023-05-17 06:30:19,925:INFO:               skopt: Not installed
2023-05-17 06:30:19,925:INFO:              mlflow: Not installed
2023-05-17 06:30:19,925:INFO:              gradio: Not installed
2023-05-17 06:30:19,925:INFO:             fastapi: Not installed
2023-05-17 06:30:19,925:INFO:             uvicorn: Not installed
2023-05-17 06:30:19,925:INFO:              m2cgen: Not installed
2023-05-17 06:30:19,925:INFO:           evidently: Not installed
2023-05-17 06:30:19,925:INFO:               fugue: Not installed
2023-05-17 06:30:19,925:INFO:           streamlit: Not installed
2023-05-17 06:30:19,925:INFO:             prophet: Not installed
2023-05-17 06:30:19,925:INFO:None
2023-05-17 06:30:19,925:INFO:Set up data.
2023-05-17 06:30:19,925:INFO:Set up train/test split.
2023-05-17 06:30:19,925:INFO:Set up index.
2023-05-17 06:30:19,925:INFO:Set up folding strategy.
2023-05-17 06:30:19,925:INFO:Assigning column types.
2023-05-17 06:30:19,925:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-05-17 06:30:19,972:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-17 06:30:19,972:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:30:20,003:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,003:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,050:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-17 06:30:20,050:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:30:20,065:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,065:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,065:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-05-17 06:30:20,112:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:30:20,144:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,144:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,175:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-17 06:30:20,206:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,206:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,206:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-05-17 06:30:20,269:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,269:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,331:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,331:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,331:INFO:Preparing preprocessing pipeline...
2023-05-17 06:30:20,347:INFO:Set up simple imputation.
2023-05-17 06:30:20,347:INFO:Finished creating preprocessing pipeline.
2023-05-17 06:30:20,362:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\Beboo\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Pregnancies', 'Glucose',
                                             'BloodPressure', 'SkinThickness',
                                             'Insulin', 'BMI',
                                             'DiabetesPedigreeFunction', 'Age',
                                             'age_bins'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose=0))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose=0)))],
         verbose=False)
2023-05-17 06:30:20,362:INFO:Creating final display dataframe.
2023-05-17 06:30:20,409:INFO:Setup _display_container:                     Description             Value
0                    Session id              6305
1                        Target           Outcome
2                   Target type            Binary
3           Original data shape         (537, 10)
4        Transformed data shape         (537, 10)
5   Transformed train set shape         (375, 10)
6    Transformed test set shape         (162, 10)
7              Numeric features                 9
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              93b6
2023-05-17 06:30:20,484:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,486:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,551:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-17 06:30:20,553:INFO:Soft dependency imported: catboost: 1.2
2023-05-17 06:30:20,554:INFO:setup() successfully completed in 0.79s...............
2023-05-17 06:30:20,554:INFO:Initializing compare_models()
2023-05-17 06:30:20,554:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-05-17 06:30:20,554:INFO:Checking exceptions
2023-05-17 06:30:20,557:INFO:Preparing display monitor
2023-05-17 06:30:20,581:INFO:Initializing Logistic Regression
2023-05-17 06:30:20,581:INFO:Total runtime is 0.0 minutes
2023-05-17 06:30:20,581:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:20,581:INFO:Initializing create_model()
2023-05-17 06:30:20,592:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:20,592:INFO:Checking exceptions
2023-05-17 06:30:20,592:INFO:Importing libraries
2023-05-17 06:30:20,592:INFO:Copying training dataset
2023-05-17 06:30:20,595:INFO:Defining folds
2023-05-17 06:30:20,595:INFO:Declaring metric variables
2023-05-17 06:30:20,598:INFO:Importing untrained model
2023-05-17 06:30:20,601:INFO:Logistic Regression Imported successfully
2023-05-17 06:30:20,609:INFO:Starting cross validation
2023-05-17 06:30:20,610:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:28,248:INFO:Calculating mean and std
2023-05-17 06:30:28,249:INFO:Creating metrics dataframe
2023-05-17 06:30:28,438:INFO:Uploading results into container
2023-05-17 06:30:28,438:INFO:Uploading model into container now
2023-05-17 06:30:28,438:INFO:_master_model_container: 1
2023-05-17 06:30:28,438:INFO:_display_container: 2
2023-05-17 06:30:28,438:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6305, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:30:28,438:INFO:create_model() successfully completed......................................
2023-05-17 06:30:28,526:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:28,526:INFO:Creating metrics dataframe
2023-05-17 06:30:28,535:INFO:Initializing K Neighbors Classifier
2023-05-17 06:30:28,535:INFO:Total runtime is 0.1325736125310262 minutes
2023-05-17 06:30:28,535:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:28,545:INFO:Initializing create_model()
2023-05-17 06:30:28,545:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:28,545:INFO:Checking exceptions
2023-05-17 06:30:28,545:INFO:Importing libraries
2023-05-17 06:30:28,545:INFO:Copying training dataset
2023-05-17 06:30:28,550:INFO:Defining folds
2023-05-17 06:30:28,550:INFO:Declaring metric variables
2023-05-17 06:30:28,554:INFO:Importing untrained model
2023-05-17 06:30:28,558:INFO:K Neighbors Classifier Imported successfully
2023-05-17 06:30:28,567:INFO:Starting cross validation
2023-05-17 06:30:28,568:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:28,676:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,676:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,677:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,682:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,691:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,708:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,710:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:28,718:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:30,985:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:30,985:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

2023-05-17 06:30:31,137:INFO:Calculating mean and std
2023-05-17 06:30:31,153:INFO:Creating metrics dataframe
2023-05-17 06:30:31,353:INFO:Uploading results into container
2023-05-17 06:30:31,353:INFO:Uploading model into container now
2023-05-17 06:30:31,353:INFO:_master_model_container: 2
2023-05-17 06:30:31,353:INFO:_display_container: 2
2023-05-17 06:30:31,353:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-05-17 06:30:31,353:INFO:create_model() successfully completed......................................
2023-05-17 06:30:31,427:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:31,427:INFO:Creating metrics dataframe
2023-05-17 06:30:31,437:INFO:Initializing Naive Bayes
2023-05-17 06:30:31,437:INFO:Total runtime is 0.18093908627827962 minutes
2023-05-17 06:30:31,448:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:31,449:INFO:Initializing create_model()
2023-05-17 06:30:31,449:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:31,449:INFO:Checking exceptions
2023-05-17 06:30:31,449:INFO:Importing libraries
2023-05-17 06:30:31,449:INFO:Copying training dataset
2023-05-17 06:30:31,453:INFO:Defining folds
2023-05-17 06:30:31,453:INFO:Declaring metric variables
2023-05-17 06:30:31,457:INFO:Importing untrained model
2023-05-17 06:30:31,465:INFO:Naive Bayes Imported successfully
2023-05-17 06:30:31,470:INFO:Starting cross validation
2023-05-17 06:30:31,470:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:32,864:INFO:Calculating mean and std
2023-05-17 06:30:32,865:INFO:Creating metrics dataframe
2023-05-17 06:30:33,063:INFO:Uploading results into container
2023-05-17 06:30:33,063:INFO:Uploading model into container now
2023-05-17 06:30:33,063:INFO:_master_model_container: 3
2023-05-17 06:30:33,063:INFO:_display_container: 2
2023-05-17 06:30:33,063:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-05-17 06:30:33,063:INFO:create_model() successfully completed......................................
2023-05-17 06:30:33,150:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:33,150:INFO:Creating metrics dataframe
2023-05-17 06:30:33,166:INFO:Initializing Decision Tree Classifier
2023-05-17 06:30:33,166:INFO:Total runtime is 0.2097545623779297 minutes
2023-05-17 06:30:33,170:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:33,170:INFO:Initializing create_model()
2023-05-17 06:30:33,170:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:33,170:INFO:Checking exceptions
2023-05-17 06:30:33,170:INFO:Importing libraries
2023-05-17 06:30:33,170:INFO:Copying training dataset
2023-05-17 06:30:33,175:INFO:Defining folds
2023-05-17 06:30:33,175:INFO:Declaring metric variables
2023-05-17 06:30:33,179:INFO:Importing untrained model
2023-05-17 06:30:33,182:INFO:Decision Tree Classifier Imported successfully
2023-05-17 06:30:33,188:INFO:Starting cross validation
2023-05-17 06:30:33,188:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:34,585:INFO:Calculating mean and std
2023-05-17 06:30:34,598:INFO:Creating metrics dataframe
2023-05-17 06:30:34,800:INFO:Uploading results into container
2023-05-17 06:30:34,800:INFO:Uploading model into container now
2023-05-17 06:30:34,800:INFO:_master_model_container: 4
2023-05-17 06:30:34,800:INFO:_display_container: 2
2023-05-17 06:30:34,800:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=6305, splitter='best')
2023-05-17 06:30:34,800:INFO:create_model() successfully completed......................................
2023-05-17 06:30:34,886:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:34,887:INFO:Creating metrics dataframe
2023-05-17 06:30:34,899:INFO:Initializing SVM - Linear Kernel
2023-05-17 06:30:34,899:INFO:Total runtime is 0.23863832553227743 minutes
2023-05-17 06:30:34,900:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:34,900:INFO:Initializing create_model()
2023-05-17 06:30:34,900:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:34,900:INFO:Checking exceptions
2023-05-17 06:30:34,900:INFO:Importing libraries
2023-05-17 06:30:34,900:INFO:Copying training dataset
2023-05-17 06:30:34,900:INFO:Defining folds
2023-05-17 06:30:34,900:INFO:Declaring metric variables
2023-05-17 06:30:34,900:INFO:Importing untrained model
2023-05-17 06:30:34,917:INFO:SVM - Linear Kernel Imported successfully
2023-05-17 06:30:34,923:INFO:Starting cross validation
2023-05-17 06:30:34,923:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:34,981:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:34,982:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:34,986:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:30:35,001:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,005:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,016:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,020:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,022:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:30:35,031:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,031:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,050:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:35,056:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 109, in __get__
    if not self.check(obj):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1199, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-17 06:30:36,282:INFO:Calculating mean and std
2023-05-17 06:30:36,282:INFO:Creating metrics dataframe
2023-05-17 06:30:36,474:INFO:Uploading results into container
2023-05-17 06:30:36,474:INFO:Uploading model into container now
2023-05-17 06:30:36,474:INFO:_master_model_container: 5
2023-05-17 06:30:36,474:INFO:_display_container: 2
2023-05-17 06:30:36,474:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=6305, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-05-17 06:30:36,474:INFO:create_model() successfully completed......................................
2023-05-17 06:30:36,547:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:36,547:INFO:Creating metrics dataframe
2023-05-17 06:30:36,563:INFO:Initializing Ridge Classifier
2023-05-17 06:30:36,563:INFO:Total runtime is 0.26636698643366497 minutes
2023-05-17 06:30:36,563:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:36,563:INFO:Initializing create_model()
2023-05-17 06:30:36,578:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:36,578:INFO:Checking exceptions
2023-05-17 06:30:36,578:INFO:Importing libraries
2023-05-17 06:30:36,578:INFO:Copying training dataset
2023-05-17 06:30:36,582:INFO:Defining folds
2023-05-17 06:30:36,583:INFO:Declaring metric variables
2023-05-17 06:30:36,586:INFO:Importing untrained model
2023-05-17 06:30:36,590:INFO:Ridge Classifier Imported successfully
2023-05-17 06:30:36,598:INFO:Starting cross validation
2023-05-17 06:30:36,599:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:36,655:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,672:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,677:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,680:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,683:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,698:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,698:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,714:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,714:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:36,714:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 71, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 298, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 73, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Beboo\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-17 06:30:37,935:INFO:Calculating mean and std
2023-05-17 06:30:37,935:INFO:Creating metrics dataframe
2023-05-17 06:30:38,132:INFO:Uploading results into container
2023-05-17 06:30:38,132:INFO:Uploading model into container now
2023-05-17 06:30:38,132:INFO:_master_model_container: 6
2023-05-17 06:30:38,132:INFO:_display_container: 2
2023-05-17 06:30:38,132:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize='deprecated', positive=False,
                random_state=6305, solver='auto', tol=0.001)
2023-05-17 06:30:38,132:INFO:create_model() successfully completed......................................
2023-05-17 06:30:38,212:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:38,212:INFO:Creating metrics dataframe
2023-05-17 06:30:38,232:INFO:Initializing Random Forest Classifier
2023-05-17 06:30:38,232:INFO:Total runtime is 0.29419877131779987 minutes
2023-05-17 06:30:38,236:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:38,236:INFO:Initializing create_model()
2023-05-17 06:30:38,236:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:38,236:INFO:Checking exceptions
2023-05-17 06:30:38,237:INFO:Importing libraries
2023-05-17 06:30:38,237:INFO:Copying training dataset
2023-05-17 06:30:38,241:INFO:Defining folds
2023-05-17 06:30:38,242:INFO:Declaring metric variables
2023-05-17 06:30:38,246:INFO:Importing untrained model
2023-05-17 06:30:38,251:INFO:Random Forest Classifier Imported successfully
2023-05-17 06:30:38,256:INFO:Starting cross validation
2023-05-17 06:30:38,256:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:40,320:INFO:Calculating mean and std
2023-05-17 06:30:40,320:INFO:Creating metrics dataframe
2023-05-17 06:30:40,522:INFO:Uploading results into container
2023-05-17 06:30:40,522:INFO:Uploading model into container now
2023-05-17 06:30:40,522:INFO:_master_model_container: 7
2023-05-17 06:30:40,522:INFO:_display_container: 2
2023-05-17 06:30:40,522:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=6305, verbose=0, warm_start=False)
2023-05-17 06:30:40,522:INFO:create_model() successfully completed......................................
2023-05-17 06:30:40,598:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:40,598:INFO:Creating metrics dataframe
2023-05-17 06:30:40,614:INFO:Initializing Quadratic Discriminant Analysis
2023-05-17 06:30:40,614:INFO:Total runtime is 0.3338922301928202 minutes
2023-05-17 06:30:40,622:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:40,622:INFO:Initializing create_model()
2023-05-17 06:30:40,622:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:40,622:INFO:Checking exceptions
2023-05-17 06:30:40,622:INFO:Importing libraries
2023-05-17 06:30:40,622:INFO:Copying training dataset
2023-05-17 06:30:40,627:INFO:Defining folds
2023-05-17 06:30:40,627:INFO:Declaring metric variables
2023-05-17 06:30:40,631:INFO:Importing untrained model
2023-05-17 06:30:40,635:INFO:Quadratic Discriminant Analysis Imported successfully
2023-05-17 06:30:40,635:INFO:Starting cross validation
2023-05-17 06:30:40,635:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:42,031:INFO:Calculating mean and std
2023-05-17 06:30:42,031:INFO:Creating metrics dataframe
2023-05-17 06:30:42,239:INFO:Uploading results into container
2023-05-17 06:30:42,239:INFO:Uploading model into container now
2023-05-17 06:30:42,239:INFO:_master_model_container: 8
2023-05-17 06:30:42,239:INFO:_display_container: 2
2023-05-17 06:30:42,239:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-05-17 06:30:42,239:INFO:create_model() successfully completed......................................
2023-05-17 06:30:42,315:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:42,315:INFO:Creating metrics dataframe
2023-05-17 06:30:42,337:INFO:Initializing Ada Boost Classifier
2023-05-17 06:30:42,337:INFO:Total runtime is 0.3626081387201945 minutes
2023-05-17 06:30:42,341:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:42,341:INFO:Initializing create_model()
2023-05-17 06:30:42,341:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:42,341:INFO:Checking exceptions
2023-05-17 06:30:42,341:INFO:Importing libraries
2023-05-17 06:30:42,341:INFO:Copying training dataset
2023-05-17 06:30:42,341:INFO:Defining folds
2023-05-17 06:30:42,341:INFO:Declaring metric variables
2023-05-17 06:30:42,341:INFO:Importing untrained model
2023-05-17 06:30:42,353:INFO:Ada Boost Classifier Imported successfully
2023-05-17 06:30:42,360:INFO:Starting cross validation
2023-05-17 06:30:42,360:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:43,959:INFO:Calculating mean and std
2023-05-17 06:30:43,961:INFO:Creating metrics dataframe
2023-05-17 06:30:44,160:INFO:Uploading results into container
2023-05-17 06:30:44,160:INFO:Uploading model into container now
2023-05-17 06:30:44,160:INFO:_master_model_container: 9
2023-05-17 06:30:44,160:INFO:_display_container: 2
2023-05-17 06:30:44,160:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=6305)
2023-05-17 06:30:44,160:INFO:create_model() successfully completed......................................
2023-05-17 06:30:44,233:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:44,233:INFO:Creating metrics dataframe
2023-05-17 06:30:44,249:INFO:Initializing Gradient Boosting Classifier
2023-05-17 06:30:44,249:INFO:Total runtime is 0.3944707989692688 minutes
2023-05-17 06:30:44,264:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:44,264:INFO:Initializing create_model()
2023-05-17 06:30:44,264:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:44,264:INFO:Checking exceptions
2023-05-17 06:30:44,265:INFO:Importing libraries
2023-05-17 06:30:44,265:INFO:Copying training dataset
2023-05-17 06:30:44,269:INFO:Defining folds
2023-05-17 06:30:44,269:INFO:Declaring metric variables
2023-05-17 06:30:44,273:INFO:Importing untrained model
2023-05-17 06:30:44,275:INFO:Gradient Boosting Classifier Imported successfully
2023-05-17 06:30:44,275:INFO:Starting cross validation
2023-05-17 06:30:44,285:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:45,984:INFO:Calculating mean and std
2023-05-17 06:30:45,984:INFO:Creating metrics dataframe
2023-05-17 06:30:46,208:INFO:Uploading results into container
2023-05-17 06:30:46,208:INFO:Uploading model into container now
2023-05-17 06:30:46,208:INFO:_master_model_container: 10
2023-05-17 06:30:46,208:INFO:_display_container: 2
2023-05-17 06:30:46,208:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=6305, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-05-17 06:30:46,208:INFO:create_model() successfully completed......................................
2023-05-17 06:30:46,284:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:46,284:INFO:Creating metrics dataframe
2023-05-17 06:30:46,306:INFO:Initializing Linear Discriminant Analysis
2023-05-17 06:30:46,306:INFO:Total runtime is 0.42876096566518146 minutes
2023-05-17 06:30:46,309:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:46,309:INFO:Initializing create_model()
2023-05-17 06:30:46,310:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:46,310:INFO:Checking exceptions
2023-05-17 06:30:46,310:INFO:Importing libraries
2023-05-17 06:30:46,310:INFO:Copying training dataset
2023-05-17 06:30:46,314:INFO:Defining folds
2023-05-17 06:30:46,315:INFO:Declaring metric variables
2023-05-17 06:30:46,318:INFO:Importing untrained model
2023-05-17 06:30:46,322:INFO:Linear Discriminant Analysis Imported successfully
2023-05-17 06:30:46,324:INFO:Starting cross validation
2023-05-17 06:30:46,324:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:47,799:INFO:Calculating mean and std
2023-05-17 06:30:47,799:INFO:Creating metrics dataframe
2023-05-17 06:30:48,016:INFO:Uploading results into container
2023-05-17 06:30:48,017:INFO:Uploading model into container now
2023-05-17 06:30:48,017:INFO:_master_model_container: 11
2023-05-17 06:30:48,018:INFO:_display_container: 2
2023-05-17 06:30:48,018:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-05-17 06:30:48,018:INFO:create_model() successfully completed......................................
2023-05-17 06:30:48,084:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:48,084:INFO:Creating metrics dataframe
2023-05-17 06:30:48,110:INFO:Initializing Extra Trees Classifier
2023-05-17 06:30:48,110:INFO:Total runtime is 0.45882237354914346 minutes
2023-05-17 06:30:48,114:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:48,114:INFO:Initializing create_model()
2023-05-17 06:30:48,114:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:48,114:INFO:Checking exceptions
2023-05-17 06:30:48,114:INFO:Importing libraries
2023-05-17 06:30:48,114:INFO:Copying training dataset
2023-05-17 06:30:48,123:INFO:Defining folds
2023-05-17 06:30:48,123:INFO:Declaring metric variables
2023-05-17 06:30:48,128:INFO:Importing untrained model
2023-05-17 06:30:48,132:INFO:Extra Trees Classifier Imported successfully
2023-05-17 06:30:48,138:INFO:Starting cross validation
2023-05-17 06:30:48,139:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:50,304:INFO:Calculating mean and std
2023-05-17 06:30:50,306:INFO:Creating metrics dataframe
2023-05-17 06:30:50,520:INFO:Uploading results into container
2023-05-17 06:30:50,520:INFO:Uploading model into container now
2023-05-17 06:30:50,520:INFO:_master_model_container: 12
2023-05-17 06:30:50,520:INFO:_display_container: 2
2023-05-17 06:30:50,520:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=6305, verbose=0, warm_start=False)
2023-05-17 06:30:50,520:INFO:create_model() successfully completed......................................
2023-05-17 06:30:50,607:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:50,607:INFO:Creating metrics dataframe
2023-05-17 06:30:50,623:INFO:Initializing Extreme Gradient Boosting
2023-05-17 06:30:50,623:INFO:Total runtime is 0.5007148782412211 minutes
2023-05-17 06:30:50,623:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:50,623:INFO:Initializing create_model()
2023-05-17 06:30:50,623:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:50,623:INFO:Checking exceptions
2023-05-17 06:30:50,623:INFO:Importing libraries
2023-05-17 06:30:50,623:INFO:Copying training dataset
2023-05-17 06:30:50,623:INFO:Defining folds
2023-05-17 06:30:50,623:INFO:Declaring metric variables
2023-05-17 06:30:50,623:INFO:Importing untrained model
2023-05-17 06:30:50,641:INFO:Extreme Gradient Boosting Imported successfully
2023-05-17 06:30:50,647:INFO:Starting cross validation
2023-05-17 06:30:50,648:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:52,400:INFO:Calculating mean and std
2023-05-17 06:30:52,400:INFO:Creating metrics dataframe
2023-05-17 06:30:52,629:INFO:Uploading results into container
2023-05-17 06:30:52,629:INFO:Uploading model into container now
2023-05-17 06:30:52,629:INFO:_master_model_container: 13
2023-05-17 06:30:52,629:INFO:_display_container: 2
2023-05-17 06:30:52,629:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)
2023-05-17 06:30:52,629:INFO:create_model() successfully completed......................................
2023-05-17 06:30:52,704:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:52,704:INFO:Creating metrics dataframe
2023-05-17 06:30:52,724:INFO:Initializing Light Gradient Boosting Machine
2023-05-17 06:30:52,724:INFO:Total runtime is 0.5357317050298055 minutes
2023-05-17 06:30:52,724:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:52,724:INFO:Initializing create_model()
2023-05-17 06:30:52,724:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:52,724:INFO:Checking exceptions
2023-05-17 06:30:52,724:INFO:Importing libraries
2023-05-17 06:30:52,724:INFO:Copying training dataset
2023-05-17 06:30:52,724:INFO:Defining folds
2023-05-17 06:30:52,724:INFO:Declaring metric variables
2023-05-17 06:30:52,740:INFO:Importing untrained model
2023-05-17 06:30:52,743:INFO:Light Gradient Boosting Machine Imported successfully
2023-05-17 06:30:52,745:INFO:Starting cross validation
2023-05-17 06:30:52,745:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:30:55,697:INFO:Calculating mean and std
2023-05-17 06:30:55,697:INFO:Creating metrics dataframe
2023-05-17 06:30:55,929:INFO:Uploading results into container
2023-05-17 06:30:55,929:INFO:Uploading model into container now
2023-05-17 06:30:55,929:INFO:_master_model_container: 14
2023-05-17 06:30:55,929:INFO:_display_container: 2
2023-05-17 06:30:55,929:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=6305, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2023-05-17 06:30:55,929:INFO:create_model() successfully completed......................................
2023-05-17 06:30:56,007:INFO:SubProcess create_model() end ==================================
2023-05-17 06:30:56,007:INFO:Creating metrics dataframe
2023-05-17 06:30:56,023:INFO:Initializing CatBoost Classifier
2023-05-17 06:30:56,023:INFO:Total runtime is 0.5907155235608419 minutes
2023-05-17 06:30:56,027:INFO:SubProcess create_model() called ==================================
2023-05-17 06:30:56,027:INFO:Initializing create_model()
2023-05-17 06:30:56,027:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:30:56,027:INFO:Checking exceptions
2023-05-17 06:30:56,027:INFO:Importing libraries
2023-05-17 06:30:56,027:INFO:Copying training dataset
2023-05-17 06:30:56,032:INFO:Defining folds
2023-05-17 06:30:56,032:INFO:Declaring metric variables
2023-05-17 06:30:56,035:INFO:Importing untrained model
2023-05-17 06:30:56,039:INFO:CatBoost Classifier Imported successfully
2023-05-17 06:30:56,041:INFO:Starting cross validation
2023-05-17 06:30:56,041:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:31:04,687:INFO:Calculating mean and std
2023-05-17 06:31:04,688:INFO:Creating metrics dataframe
2023-05-17 06:31:04,916:INFO:Uploading results into container
2023-05-17 06:31:04,916:INFO:Uploading model into container now
2023-05-17 06:31:04,916:INFO:_master_model_container: 15
2023-05-17 06:31:04,916:INFO:_display_container: 2
2023-05-17 06:31:04,916:INFO:<catboost.core.CatBoostClassifier object at 0x0000020341C5E4C0>
2023-05-17 06:31:04,916:INFO:create_model() successfully completed......................................
2023-05-17 06:31:05,002:INFO:SubProcess create_model() end ==================================
2023-05-17 06:31:05,002:INFO:Creating metrics dataframe
2023-05-17 06:31:05,011:INFO:Initializing Dummy Classifier
2023-05-17 06:31:05,011:INFO:Total runtime is 0.7405067165692647 minutes
2023-05-17 06:31:05,011:INFO:SubProcess create_model() called ==================================
2023-05-17 06:31:05,011:INFO:Initializing create_model()
2023-05-17 06:31:05,011:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000002034199A850>, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:31:05,011:INFO:Checking exceptions
2023-05-17 06:31:05,011:INFO:Importing libraries
2023-05-17 06:31:05,011:INFO:Copying training dataset
2023-05-17 06:31:05,021:INFO:Defining folds
2023-05-17 06:31:05,021:INFO:Declaring metric variables
2023-05-17 06:31:05,025:INFO:Importing untrained model
2023-05-17 06:31:05,028:INFO:Dummy Classifier Imported successfully
2023-05-17 06:31:05,033:INFO:Starting cross validation
2023-05-17 06:31:05,033:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-17 06:31:05,111:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,111:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,127:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,127:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,142:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,158:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,158:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,173:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,173:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:05,189:WARNING:C:\Users\Beboo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-17 06:31:06,613:INFO:Calculating mean and std
2023-05-17 06:31:06,613:INFO:Creating metrics dataframe
2023-05-17 06:31:06,836:INFO:Uploading results into container
2023-05-17 06:31:06,836:INFO:Uploading model into container now
2023-05-17 06:31:06,836:INFO:_master_model_container: 16
2023-05-17 06:31:06,836:INFO:_display_container: 2
2023-05-17 06:31:06,836:INFO:DummyClassifier(constant=None, random_state=6305, strategy='prior')
2023-05-17 06:31:06,836:INFO:create_model() successfully completed......................................
2023-05-17 06:31:06,926:INFO:SubProcess create_model() end ==================================
2023-05-17 06:31:06,926:INFO:Creating metrics dataframe
2023-05-17 06:31:06,952:INFO:Initializing create_model()
2023-05-17 06:31:06,952:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000020334D69040>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6305, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-05-17 06:31:06,953:INFO:Checking exceptions
2023-05-17 06:31:06,954:INFO:Importing libraries
2023-05-17 06:31:06,954:INFO:Copying training dataset
2023-05-17 06:31:06,957:INFO:Defining folds
2023-05-17 06:31:06,958:INFO:Declaring metric variables
2023-05-17 06:31:06,958:INFO:Importing untrained model
2023-05-17 06:31:06,958:INFO:Declaring custom model
2023-05-17 06:31:06,958:INFO:Logistic Regression Imported successfully
2023-05-17 06:31:06,959:INFO:Cross validation set to False
2023-05-17 06:31:06,959:INFO:Fitting Model
2023-05-17 06:31:07,177:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6305, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:31:07,177:INFO:create_model() successfully completed......................................
2023-05-17 06:31:07,277:INFO:_master_model_container: 16
2023-05-17 06:31:07,277:INFO:_display_container: 2
2023-05-17 06:31:07,277:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6305, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-17 06:31:07,277:INFO:compare_models() successfully completed......................................
